import { Component, OnInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ChecklistService } from '../../../services/checklist.service';
import { TranslationService } from '../../../services/translation.service';
import { NotificationService } from '../../../core/services/notification.service';
import { MaintenanceChecklist, ChecklistItem } from '../../../models';

@Component({
  selector: 'app-checklist-manager',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './checklist-manager.component.html',
  styleUrl: './checklist-manager.component.css'
})
export class ChecklistManagerComponent implements OnInit {
  private checklistService = inject(ChecklistService);
  private notificationService = inject(NotificationService);
  public t = inject(TranslationService);
  
  checklists = signal<MaintenanceChecklist[]>([]);
  loading = signal(false);
  
  // Edit form
  showEditForm = signal(false);
  editingChecklist = signal<MaintenanceChecklist | null>(null);
  editForm = {
    name: '',
    description: '',
    deviceType: '',
    isActive: true
  };
  
  // Item management
  showItemForm = signal(false);
  editingItem = signal<ChecklistItem | null>(null);
  selectedChecklistId = signal<string | null>(null);
  itemForm = {
    orderIndex: 0,
    taskDescription: '',
    isMandatory: true,
    estimatedMinutes: 0,
    safetyNote: ''
  };

  ngOnInit() {
    this.loadChecklists();
  }

  async loadChecklists() {
    try {
      this.loading.set(true);
      const data = await this.checklistService.getAllChecklists();
      
      // Načítať počet položiek pre každý checklist
      const checklistsWithCounts = await Promise.all(
        data.map(async (checklist) => {
          try {
            // Načítať položky pre tento checklist
            const tokenData = localStorage.getItem('supabase.auth.token');
            let accessToken = null;
            if (tokenData) {
              const parsed = JSON.parse(tokenData);
              accessToken = parsed.access_token;
            }

            const response = await fetch(`https://mplehgphscavhyxebzvo.supabase.co/rest/v1/checklist_items?checklist_id=eq.${checklist.id}&select=*`, {
              method: 'GET',
              headers: {
                'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbGVoZ3Boc2Nhdmh5eGVienZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4NDIzMTksImV4cCI6MjA4MzQxODMxOX0.v-IcZBn3BbYFoUWMoZppKGVtr31FvYNmVJeSz0Klhlw',
                'Authorization': `Bearer ${accessToken}`
              }
            });

            if (response.ok) {
              const items = await response.json();
              return { ...checklist, items: items || [] };
            }
            return { ...checklist, items: [] };
          } catch (err) {
            console.error('Error loading items for checklist:', checklist.id, err);
            return { ...checklist, items: [] };
          }
        })
      );
      
      this.checklists.set(checklistsWithCounts);
    } catch (error) {
      this.notificationService.error('Chyba pri načítavaní checklistov');
    } finally {
      this.loading.set(false);
    }
  }

  // Checklist CRUD
  openNewChecklistForm() {
    this.editingChecklist.set(null);
    this.editForm = {
      name: '',
      description: '',
      deviceType: '',
      isActive: true
    };
    this.showEditForm.set(true);
  }

  openEditChecklistForm(checklist: MaintenanceChecklist) {
    this.editingChecklist.set(checklist);
    // Database returns snake_case, access both for safety
    const isActive = (checklist as any).is_active ?? checklist.isActive ?? true;
    this.editForm = {
      name: checklist.name,
      description: checklist.description || '',
      deviceType: (checklist as any).device_type || checklist.deviceType,
      isActive: isActive
    };
    this.showEditForm.set(true);
  }

  async saveChecklist() {
    try {
      this.loading.set(true);
      
      // Transform camelCase to snake_case for database
      const dbData = {
        device_type: this.editForm.deviceType,
        name: this.editForm.name,
        description: this.editForm.description,
        is_active: this.editForm.isActive
      };
      
      if (this.editingChecklist()) {
        // Update
        await this.checklistService.updateChecklist(
          this.editingChecklist()!.id,
          dbData as any
        );
      } else {
        // Create - ID is auto-generated by database
        await this.checklistService.createChecklist(dbData as any);
      }
      
      this.showEditForm.set(false);
      await this.loadChecklists();
    } catch (error) {
      this.notificationService.error(`Chyba pri ukladaní checklistu: ${error instanceof Error ? error.message : JSON.stringify(error)}`);
    } finally {
      this.loading.set(false);
    }
  }

  async deleteChecklist(id: string) {
    if (!confirm('Naozaj chcete vymazať tento checklist a všetky jeho položky?')) {
      return;
    }

    try {
      this.loading.set(true);
      await this.checklistService.deleteChecklist(id);
      await this.loadChecklists();
    } catch (error) {
      this.notificationService.error('Chyba pri mazaní checklistu');
    } finally {
      this.loading.set(false);
    }
  }

  // Item CRUD
  openItemsManager(checklist: MaintenanceChecklist) {
    this.selectedChecklistId.set(checklist.id);
    this.loadChecklistItems(checklist.id);
  }

  async loadChecklistItems(checklistId: string) {
    try {
      const checklist = await this.checklistService.getChecklistWithItems(checklistId);
      // Update the checklist in our list with loaded items
      const list = this.checklists();
      const index = list.findIndex(c => c.id === checklistId);
      if (index >= 0) {
        list[index] = checklist;
        this.checklists.set([...list]);
      }
    } catch (error) {
      console.error('Error loading checklist items:', error);
    }
  }

  openNewItemForm(checklistId: string) {
    this.selectedChecklistId.set(checklistId);
    this.editingItem.set(null);
    const checklist = this.checklists().find(c => c.id === checklistId);
    const maxOrder = checklist?.items?.reduce((max, item) => Math.max(max, item.orderIndex), 0) || 0;
    
    this.itemForm = {
      orderIndex: maxOrder + 1,
      taskDescription: '',
      isMandatory: true,
      estimatedMinutes: 0,
      safetyNote: ''
    };
    this.showItemForm.set(true);
  }

  openEditItemForm(item: ChecklistItem) {
    this.editingItem.set(item);
    this.itemForm = {
      orderIndex: (item as any).order_index,
      taskDescription: (item as any).task_description,
      isMandatory: (item as any).is_mandatory,
      estimatedMinutes: (item as any).estimated_minutes || 0,
      safetyNote: (item as any).safety_note || ''
    };
    this.showItemForm.set(true);
  }

  async saveItem() {
    try {
      this.loading.set(true);
      
      // Transform camelCase to snake_case for database
      const dbData = {
        order_index: this.itemForm.orderIndex,
        task_description: this.itemForm.taskDescription,
        is_mandatory: this.itemForm.isMandatory,
        estimated_minutes: this.itemForm.estimatedMinutes,
        safety_note: this.itemForm.safetyNote
      };
      
      if (this.editingItem()) {
        // Update
        await this.checklistService.updateChecklistItem(
          this.editingItem()!.id,
          dbData as any
        );
      } else {
        // Create
        await this.checklistService.addChecklistItem({
          ...dbData,
          checklist_id: this.selectedChecklistId()!
        } as any);
      }
      
      this.showItemForm.set(false);
      await this.loadChecklistItems(this.selectedChecklistId()!);
    } catch (error) {
      this.notificationService.error('Chyba pri ukladaní položky');
    } finally {
      this.loading.set(false);
    }
  }

  async deleteItem(itemId: string, checklistId: string) {
    if (!confirm('Naozaj chcete vymazať túto položku?')) {
      return;
    }

    try {
      this.loading.set(true);
      await this.checklistService.deleteChecklistItem(itemId);
      await this.loadChecklistItems(checklistId);
    } catch (error) {
      this.notificationService.error('Chyba pri mazaní položky');
    } finally {
      this.loading.set(false);
    }
  }

  closeItemsManager() {
    this.selectedChecklistId.set(null);
  }

  getChecklist(id: string): MaintenanceChecklist | undefined {
    return this.checklists().find(c => c.id === id);
  }
}
